### ISSUE TITLE
client side sendSignTransaction 

### ISSUE THREAD

**Issue by MASDXI** [qtumproject/janus#79] opened 2021-08-31 09:07 UTC
can't transfer token with metamask

**Comment by VoR0220** [comment] 2021-09-02 18:51
Can you show us reproduction steps?

**Comment by MASDXI** [comment] 2021-09-03 03:26
qtum node running in regtest mode
starting janus
```  
$ export QTUM_RPC="http://x:y@127.0.0.1:8545"
$ janus --bind 127.0.0.1 --accounts ../myaccounts.txt --dev --qtum-network="regtest" --qtum-rpc=$QTUM_RPC
```   
![qtum-janus-issue](https://user-images.githubusercontent.com/31649128/131945845-ff1481c2-9c4b-4700-ace9-915803074ee6.png)  

![qtum-janus-issue02](https://user-images.githubusercontent.com/31649128/131945849-8010f374-7ce7-4d20-9bc7-abadaaea8c46.png)

**Comment by VoR0220** [comment] 2021-09-03 16:21
We actually had to fork metamask because metamask has issues with signing and serializing and deserializing qtum style transactions. If you'd like to take a look at our fork, you can find it here and try building it from there: https://github.com/earlgreytech/metamask-extension/tree/v10.0.2.QTUM

hopefully that works better.

**Comment by MASDXI** [comment] 2021-09-06 05:15
> We actually had to fork metamask because metamask has issues with signing and serializing and deserializing qtum style transactions. If you'd like to take a look at our fork, you can find it here and try building it from there: https://github.com/earlgreytech/metamask-extension/tree/v10.0.2.QTUM
> 
> hopefully that works better.

everything works better janus + customized metamask v.Qtum

found issue
contract address mixed case checksum [EIP-55]
contract not return in Remix IDE

**Comment by ripply** [comment] 2022-07-19 19:05
Closing this, our MetaMask fork has come a long way.

For future reference, contract address generation is different from Ethereum and Janus should return the correct address in the transaction receipt. If you need to compute the address before the transaction is mined then you can do that with https://github.com/qtumproject/qtum-ethers/

truffle support is ongoing but local transaction signing works with https://www.npmjs.com/package/@qtumproject/hdwallet-provider

**Closed by ripply** 2022-07-19 19:05 UTC
